### ISSUE TITLE
Holding a note over rhythm exercises

### ISSUE THREAD

**Issue by practicingmusician** [practicing-musician/PracticingMusicianListener#22]
When I hold a note over rhythm exercises, some notes are counted as early but many are counted as correct.  See video "Holding a note in rhythm exercises" in email.

**Comment by jnpdx** [comment]
The problem with playing an exercise 100% incorrectly is that it makes it extraordinarily difficult for the listener to make good guesses about what is going on.  I think I'm going to close this one for now as it isn't a specific bug and also probably an unrealistic scenario.  Hopefully it'll improve with refinement, but there's nothing to be done specifically for now.
