### ISSUE TITLE
Playing during rests

### ISSUE THREAD

**Issue by practicingmusician** [practicing-musician/PracticingMusicianListener#23]
I played over all the rests on Oh When The Saints Go Marching In, and a different number are analyzed correctly each time.  See "Playing during rests" video in email.

**Comment by practicingmusician** [comment]
Just received another strange error on a rest.  See attached
![screen shot 2019-02-13 at 1 03 12 pm](https://user-images.githubusercontent.com/31043736/52743820-c3019380-2f8f-11e9-9437-dfb8df728aa5.png)

**Comment by jnpdx** [comment]
New version will only say "MISSED" and not report the other errors if it is on a rest.  It will also report "REST" instead of "NOTE"
