### ISSUE TITLE
Flat sign on listener analysis

### ISSUE THREAD

**Issue by practicingmusician** [practicing-musician/PracticingMusicianListener#36]
I just discovered that the flat sign on the listener analysis is actually a capital B instead of a lower case b.  See attached.
![Screen Shot 2019-04-12 at 1 01 46 PM](https://user-images.githubusercontent.com/31043736/56063166-60284080-5d23-11e9-804f-c0c20f1ffea5.png)

**Comment by jnpdx** [comment]
Addressed in f420372

Will be fixed in next update to the site
