### ISSUE TITLE
Flat symbol on assessment

### ISSUE THREAD

**Issue by practicingmusician** [practicing-musician/PracticingMusicianListener#40]
Flat symbol on assessment is still a capital B.  Needs to be lower case.
![Screen Shot 2019-06-06 at 11 03 10 AM](https://user-images.githubusercontent.com/31043736/59055463-b9f04700-884a-11e9-8df6-f3b2d2a8b637.png)

**Comment by jnpdx** [comment]
Hadn't updated the site yet even though the code was fixed.  Updating now.
